In [1]:
!pip install keras

In [22]:
!pip install pickle5

  Using cached pickle5-0.0.11.tar.gz (132 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Running setup.py clean for pickle5
Failed to build pickle5


  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [38 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\pickle5
  copying pickle5\pickle.py -> build\lib.win-amd64-cpython-310\pickle5
  copying pickle5\pickletools.py -> build\lib.win-amd64-cpython-310\pickle5
  copying pickle5\__init__.py -> build\lib.win-amd64-cpython-310\pickle5
  creating build\lib.win-amd64-cpython-310\pickle5\test
  copying pickle5\test\pickletester.py -> build\lib.win-amd64-cpython-310\pickle5\test
  copying pickle5\test\test_pickle.py -> build\lib.win-amd64-cpython-310\pickle5\test
  copying pickle5\test\test_picklebuffer.py -> build\lib.win-amd64-cpython-310\pickle5\test
  copying pickle5\test\__init__.py -> build\lib.win-amd64-cpython-310\pickle5\test
  running build_ext
  building 'pickle5._pickle' extension
  creating 

In [3]:
!pip install wordcloud

                                              0.0/152.1 kB ? eta -:--:--
     ---------                             41.0/152.1 kB 960.0 kB/s eta 0:00:01
     -------------------------------------- 152.1/152.1 kB 2.3 MB/s eta 0:00:00


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [5]:
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
import json
#import pickle5 as pickle
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout
from keras.optimizers import SGD
import random
import matplotlib.pyplot as plt
import csv
from wordcloud import WordCloud

In [23]:
from keras.layers import LSTM,Embedding

# #Model Building

In [6]:
words=[]
classes = []
documents = []
ignore_words = ['?', '!']
data_file_iclinicQA = open("C:\python_project\Dataset\iclinicQA_clean_tag.json").read()
intents = json.loads(data_file_iclinicQA)

In [7]:
for pattern in intents:
  #tokenize each word
  w = nltk.word_tokenize(pattern['final_question'])
  words.extend(w)
  #add documents in the corpus
  documents.append((w, pattern['final_tag']))
  # add to our classes list
  if pattern['final_tag'] not in classes:
    classes.append(pattern['final_tag'])

In [8]:
import nltk
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()


In [9]:
# lemmatize, lower each word and remove duplicates
words = [w.lower() for w in words if w not in ignore_words]
words = sorted(list(set(words)))
# sort classes
classes = sorted(list(set(classes)))
# documents = combination between patterns and intents
print(len(documents), "documents")
# classes = intents
print(len(classes), "classes", classes)
# words = all words, vocabulary
print(len(words), "unique lemmatized words", words)
pickle.dump(words,open('words.pkl','wb'))
pickle.dump(classes,open('classes.pkl','wb'))

465 documents
79 classes ['acid reflux', 'acne', 'acne scar', 'allergy', 'amoxicillin', 'angiography', 'antibiotic', 'anxiety', 'arrhythmia', 'baby constipation', 'benzoyl peroxide', 'blood pressure monitor', 'breast feeding', 'chest x- ray', 'complete blood count', 'conception pregnancy', 'constipation', 'contraceptive pill', 'coronary artery disease', 'delayed period', 'dental scaling', 'depression', 'diabetes', 'ecg', 'ectopic pregnancy', 'erectile dysfunction', 'exercise', 'eye examination', 'fexofenadine', 'folic acid', 'fungal infection', 'genetic inheritance', 'gerd', 'hairfall', 'headache', 'heavy bleeding', 'hiv', 'hiv infection', 'hot fomentation', 'hypothyroidism', 'kidney stone', 'knee pain', 'levocetirizine', 'liver function test', 'masturbation', 'migraine', 'missed period', 'mri', 'numbness', 'omega fatty acid', 'oral hygiene maintenance', 'overweight', 'physiotherapy', 'prednisolone', 'pregnancy', 'premature ejaculation', 'psychological counselling', 'reduce weight', 'r

NameError: name 'pickle' is not defined

In [10]:
type(documents)

list

In [11]:
print(documents[:10])

[(['fine', 'exercise', 'knee', 'pain'], 'exercise'), (['suffering', 'anxiety', 'restlessness', 'taking', 'clonazepam', 'mirtazapine', 'depression', 'panic', 'attack', 'last', '7', 'year', 'need', 'second', 'opinion'], 'anxiety'), (['thyroid', 'patient', 'eat', 'soybean', 'fenugreek'], 'hypothyroidism'), (['getting', 'period', 'taking', 'fenugreek', 'seed'], 'delayed period'), (['kindly', 'suggest', 'therapy', 'overcome', 'heat', 'allergy'], 'levocetirizine'), (['taking', 'multiple', 'antibiotic', 'cause', 'redness', 'dryness', 'vagina'], 'antibiotic'), (['baclofen', 'medicine', 'used', 'muscle', 'stiffness'], 'physiotherapy'), (['fiance', 'diabetes', 'type', '2', 'face', 'problem', 'pregnancy'], 'diabetes'), (['one', 'hair', 'eyebrow', 'changed', 'blond', 'normal'], 'vitiligo'), (['son', 'severe', 'constipation', 'taking', 'paxil', 'please', 'help'], 'constipation')]


In [12]:
print(words)

['10', '12', '13', '14', '15', '18th', '1st', '2', '20', '23', '26', '2g', '3', '30', '4', '40', '42', '43', '45', '5', '50', '500', '5mg', '5th', '7', '78kgs', '8', '9', '9th', 'abdomen', 'able', 'abnormal', 'abortion', 'abrupt', 'abscess', 'absence', 'accurate', 'accutane', 'achalasia', 'achieve', 'acid', 'acidity', 'acne', 'act', 'add', 'adenomyosis', 'admission', 'advice', 'advise', 'affect', 'afib', 'age', 'ago', 'alarming', 'allergic', 'allergy', 'along', 'also', 'alternative', 'always', 'amniocentesis', 'amoxicillin', 'anal', 'andersson', 'aneurysm', 'anger', 'angio', 'ankylosing', 'antianxiety', 'antibiotic', 'antihistamine', 'anxiety', 'anything', 'appetite', 'application', 'applying', 'apt', 'arm', 'artery', 'arthritis', 'asleep', 'assuming', 'asthma', 'asthmatic', 'atenolol', 'atorvastatin', 'attack', 'attracted', 'augmentin', 'avoid', 'ayurveda', 'ayurvedic', 'b', 'b12', 'baby', 'back', 'backside', 'baclofen', 'bad', 'badly', 'bear', 'become', 'becoming', 'belly', 'benzoyl'

In [13]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\Sunil
[nltk_data]     Bhagwat\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [14]:
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to C:\Users\Sunil
[nltk_data]     Bhagwat\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [15]:
# create our training data
training = []
# create an empty array for our output
output_empty = [0] * len(classes)
# training set, bag of words for each sentence
for doc in documents:
    # initialize our bag of words
    bag = []
    # list of tokenized words for the pattern
    pattern_words = doc[0]
    # lemmatize each word - create base word, in attempt to represent related words
    pattern_words = [lemmatizer.lemmatize(word.lower()) for word in pattern_words]
# create our bag of words array with 1, if word match found in current pattern
    for w in words:
        bag.append(1) if w in pattern_words else bag.append(0)
    # output is a '0' for each tag and '1' for current tag (for each pattern)
    output_row = list(output_empty)
    output_row[classes.index(doc[1])] = 1
    training.append([bag, output_row])
# shuffle our features and turn into np.array
random.shuffle(training)
training = np.array(training)
# create train and test lists. X - patterns, Y - intents
train_x = list(training[:,0])
train_y = list(training[:,1])
print("Training data created")

Training data created


C:\Users\Sunil Bhagwat\AppData\Local\Temp\ipykernel_3440\2726551193.py:22: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  training = np.array(training)


In [53]:
len(train_y)

465

In [16]:
# Create model - 3 layers. First layer 128 neurons, second layer 64 neurons and 
# 3rd output layer contains number of neurons
# equal to number of intents to predict output intent with softmax
model = Sequential()
model.add(Dense(128, input_shape=(len(train_x[0]),), activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(len(train_y[0]), activation='softmax'))
# Compile model. Stochastic gradient descent with Nesterov accelerated gradient gives good results for this model
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])
#fitting and saving the model 
hist = model.fit(np.array(train_x), np.array(train_y), epochs=100, batch_size=5, verbose=1)
model.save('chatbot_model.h5', hist)
print("model created")

C:\Users\Sunil Bhagwat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\keras\optimizers\legacy\gradient_descent.py:114: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


Epoch 1/100
93/93 [==============================] - 1s 2ms/step - loss: 4.3692 - accuracy: 0.0172
Epoch 2/100
93/93 [==============================] - 0s 3ms/step - loss: 4.3147 - accuracy: 0.0366
Epoch 3/100
93/93 [==============================] - 0s 2ms/step - loss: 4.2714 - accuracy: 0.0516
Epoch 4/100
93/93 [==============================] - 0s 2ms/step - loss: 4.1777 - accuracy: 0.0710
Epoch 5/100
93/93 [==============================] - 0s 2ms/step - loss: 4.0505 - accuracy: 0.1075
Epoch 6/100
93/93 [==============================] - 0s 2ms/step - loss: 3.8583 - accuracy: 0.1548
Epoch 7/100
93/93 [==============================] - 0s 2ms/step - loss: 3.6459 - accuracy: 0.1978
Epoch 8/100
93/93 [==============================] - 0s 2ms/step - loss: 3.3800 - accuracy: 0.2301
Epoch 9/100
93/93 [==============================] - 0s 2ms/step - loss: 3.1765 - accuracy: 0.2602
Epoch 10/100
93/93 [==============================] - 0s 2ms/step - loss: 2.8211 - accuracy: 0.3591
Epoch 11/

93/93 [==============================] - 0s 2ms/step - loss: 0.4122 - accuracy: 0.8559
Epoch 84/100
93/93 [==============================] - 0s 3ms/step - loss: 0.4321 - accuracy: 0.8645
Epoch 85/100
93/93 [==============================] - 0s 3ms/step - loss: 0.4974 - accuracy: 0.8710
Epoch 86/100
93/93 [==============================] - 0s 3ms/step - loss: 0.5632 - accuracy: 0.8323
Epoch 87/100
93/93 [==============================] - 0s 3ms/step - loss: 0.5019 - accuracy: 0.8409
Epoch 88/100
93/93 [==============================] - 0s 3ms/step - loss: 0.5527 - accuracy: 0.8430
Epoch 89/100
93/93 [==============================] - 0s 3ms/step - loss: 0.4836 - accuracy: 0.8602
Epoch 90/100
93/93 [==============================] - 0s 3ms/step - loss: 0.4681 - accuracy: 0.8516
Epoch 91/100
93/93 [==============================] - 0s 3ms/step - loss: 0.5251 - accuracy: 0.8430
Epoch 92/100
93/93 [==============================] - 0s 3ms/step - loss: 0.4401 - accuracy: 0.8645
Epoch 93/100


In [24]:
def clean_up_sentence(sentence):
    # tokenize the pattern - split words into array
    sentence_words = nltk.word_tokenize(sentence)
    # stem each word - create short form for word
    sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]
    return sentence_words
# return bag of words array: 0 or 1 for each word in the bag that exists in the sentence
def bow(sentence, words, show_details=True):
    # tokenize the pattern
    sentence_words = clean_up_sentence(sentence)
    # bag of words - matrix of N words, vocabulary matrix
    bag = [0]*len(words)
    for s in sentence_words:
        for i,w in enumerate(words):
            if w == s: 
                # assign 1 if current word is in the vocabulary position
                bag[i] = 1
                if show_details:
                    print ("found in bag: %s" % w)
    return(np.array(bag))
def predict_class(sentence, model):
    # filter out predictions below a threshold
    p = bow(sentence, words,show_details=False)
    res = model.predict(np.array([p]))[0]
    ERROR_THRESHOLD = 0.25
    results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]
    # sort by strength of probability
    results.sort(key=lambda x: x[1], reverse=True)
    return_list = []
    
    for r in results:
        return_list.append({"intent": classes[r[0]], "probability": str(r[1])})
    return return_list

In [25]:
def getResponse(ints, intents_json):
    tag = ints[0]['intent']
    list_of_intents = intents_json    
    for i in list_of_intents:
        if(i['final_tag']== tag):
            result = i['final_answer']
            break
    return result

def chatbot_response(text):
    ints = predict_class(text, model)
    res = getResponse(ints, intents)
    return res

In [26]:
qn = 'is it fine to exercise with knee pain?'
chatbot_response(qn)

1/1 [==============================] - 0s 372ms/step


'description appears may anterior knee pain sometimes present pain back knee second possibility done exercise hamstring sore lower end knee cap inflamed either way rest ice area pain give time suggest add nsaid nonsteroidal antiinflammatory drug week additional antiinflammatory action information consult orthopaedician traumatologist online'

# # LSTM Model

In [108]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [109]:
### Vocabulary size
voc_size=5000

In [110]:
df_lstm = pd.read_json("C:\python_project\Dataset\iclinicQA_clean_tag.json")
df_lstm.head()

final_answer  \
0  description appears may anterior knee pain som...   
1  depression anxiety restlessness panic attack b...   
2  patient hypothyroidism usually gain weight iss...   
3  fenugreek seed cannot affect fertility worry d...   
4  problem characteristic cholinergic urticaria t...   

                                      final_question       final_tag  
0                            fine exercise knee pain        exercise  
1  suffering anxiety restlessness taking clonazep...         anxiety  
2              thyroid patient eat soybean fenugreek  hypothyroidism  
3               getting period taking fenugreek seed  delayed period  
4       kindly suggest therapy overcome heat allergy  levocetirizine

In [ ]:
#X= 

In [111]:
import nltk
import re
from nltk.corpus import stopwords

In [31]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Sunil
[nltk_data]     Bhagwat\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [112]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(df_lstm)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', df_lstm['final_question'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

In [113]:
corpus

['fine exercis knee pain',
 'suffer anxieti restless take clonazepam mirtazapin depress panic attack last year need second opinion',
 'thyroid patient eat soybean fenugreek',
 'get period take fenugreek seed',
 'kindli suggest therapi overcom heat allergi',
 'take multipl antibiot caus red dryness vagina',
 'baclofen medicin use muscl stiff',
 'fianc diabet type face problem pregnanc',
 'one hair eyebrow chang blond normal',
 'son sever constip take paxil pleas help',
 'son continu chest congest',
 'essenti tremor get transfer genet',
 'applic selsun blue shampoo cheek turn white pleas help',
 'absenc white half moon nail indic thyroid problem',
 'feel weak sit work',
 'leucoderma curabl',
 'control prematur ejacul',
 'psychiatr drug induc constip',
 'treat prematur ejacul ayurveda',
 'thyroid problem hr bp fluctuat often',
 'cure prematur ejacul',
 'overcom prematur ejacul',
 'prematur ejacul due fear lifelong problem',
 'overcom prematur ejacul use ayurved medicin',
 'suffer prematur

In [114]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[2762, 156, 3310, 3506],
 [455,
  1789,
  1930,
  1751,
  4514,
  3120,
  4937,
  3249,
  241,
  3064,
  3682,
  4076,
  448,
  2116],
 [4596, 4934, 1084, 2968, 2210],
 [266, 1297, 1751, 2210, 2029],
 [1638, 550, 2700, 4301, 2317, 326],
 [1751, 4867, 528, 2896, 1312, 1570, 148],
 [2822, 481, 2023, 407, 1748],
 [1078, 3620, 3607, 2719, 4011, 1179],
 [2083, 3391, 1393, 4916, 1617, 3708],
 [1778, 2362, 133, 1751, 956, 2155, 987],
 [1778, 256, 2050, 1873],
 [367, 3572, 266, 3528, 3096],
 [2547, 3792, 1837, 549, 4329, 734, 2729, 2155, 987],
 [2282, 2729, 4243, 2486, 3077, 439, 4596, 4011],
 [3940, 2864, 1262, 4311],
 [4282, 3799],
 [2812, 2767, 2131],
 [262, 1864, 4603, 133],
 [537, 2767, 2131, 3117],
 [4596, 4011, 2163, 4270, 1354, 760],
 [338, 2767, 2131],
 [4301, 2767, 2131],
 [2767, 2131, 622, 1318, 2174, 4011],
 [4301, 2767, 2131, 2023, 3730, 481],
 [455, 2767, 2131, 2131, 3814, 2420, 2278, 712],
 [2719, 2767, 2131, 4301],
 [4596, 4011, 726, 1179],
 [3719, 468, 734, 2729],
 [3698, 276

In [115]:
sent_length=1064
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ...  156 3310 3506]
 [   0    0    0 ... 4076  448 2116]
 [   0    0    0 ... 1084 2968 2210]
 ...
 [   0    0    0 ... 4118 1751   57]
 [   0    0    0 ... 1074  241 4934]
 [   0    0    0 ... 4076  448 2116]]


In [116]:
embedded_docs[0]

array([   0,    0,    0, ...,  156, 3310, 3506])

In [117]:
len(train_y)

465

In [119]:
## Creating model
embedding_vector_features=40
model_lstm=Sequential()
model_lstm.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model_lstm.add(LSTM(100))
model_lstm.add(Dense(len(y_train1[0]),activation='softmax'))
model_lstm.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model_lstm.summary())

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 1064, 40)          200000    
                                                                 
 lstm_9 (LSTM)               (None, 100)               56400     
                                                                 
 dense_13 (Dense)            (None, 79)                7979      
                                                                 
Total params: 264,379
Trainable params: 264,379
Non-trainable params: 0
_________________________________________________________________
None


In [120]:
y = df_lstm['final_tag']

In [121]:
len(embedded_docs),y.shape

(465, (465,))

In [122]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [123]:
X_final.shape,y_final.shape

((465, 1064), (465,))

In [124]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.2, random_state=42)

In [125]:
print(y_train[0])

genetic inheritance


In [126]:
final_y = np.array(train_y)

In [127]:
print(final_y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [128]:
final_tag_list = []
for tag in y:
    m_lst= []
    m_lst.append(tag)
    final_tag_list.append(m_lst)
print(final_tag_list)

[['exercise'], ['anxiety'], ['hypothyroidism'], ['delayed period'], ['levocetirizine'], ['antibiotic'], ['physiotherapy'], ['diabetes'], ['vitiligo'], ['constipation'], ['complete blood count'], ['genetic inheritance'], ['vitiligo'], ['thyroid problem'], ['thyroid problem'], ['vitiligo'], ['premature ejaculation'], ['constipation'], ['premature ejaculation'], ['thyroid problem'], ['premature ejaculation'], ['premature ejaculation'], ['premature ejaculation'], ['premature ejaculation'], ['premature ejaculation'], ['premature ejaculation'], ['thyroid problem'], ['vitiligo'], ['premature ejaculation'], ['thyroid problem'], ['thyroid problem'], ['complete blood count'], ['premature ejaculation'], ['complete blood count'], ['constipation'], ['vitiligo'], ['complete blood count'], ['constipation'], ['constipation'], ['levocetirizine'], ['levocetirizine'], ['constipation'], ['genetic inheritance'], ['levocetirizine'], ['genetic inheritance'], ['constipation'], ['genetic inheritance'], ['levoc

In [129]:
from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data
data = asarray(final_tag_list)
#print(data)
# define one hot encoding
encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


C:\Users\Sunil Bhagwat\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\sklearn\preprocessing\_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [130]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_final, onehot, test_size=0.2, random_state=42)

In [131]:
len(y_train1[0])

79

In [132]:
### Finally Training
model_lstm.fit(X_train1,y_train1,validation_data=(X_test1,y_test1),epochs=100,batch_size=5)

Epoch 1/100
75/75 [==============================] - 25s 302ms/step - loss: 4.3688 - accuracy: 0.0134 - val_loss: 4.3701 - val_accuracy: 0.0323
Epoch 2/100
75/75 [==============================] - 21s 276ms/step - loss: 4.3311 - accuracy: 0.0323 - val_loss: 4.3907 - val_accuracy: 0.0215
Epoch 3/100
75/75 [==============================] - 20s 268ms/step - loss: 4.2579 - accuracy: 0.0565 - val_loss: 4.3729 - val_accuracy: 0.0323
Epoch 4/100
75/75 [==============================] - 23s 314ms/step - loss: 4.3269 - accuracy: 0.0296 - val_loss: 4.5751 - val_accuracy: 0.0000e+00
Epoch 5/100
75/75 [==============================] - 25s 334ms/step - loss: 4.2043 - accuracy: 0.0806 - val_loss: 4.2619 - val_accuracy: 0.0968
Epoch 6/100
75/75 [==============================] - 28s 369ms/step - loss: 4.0775 - accuracy: 0.1317 - val_loss: 4.3084 - val_accuracy: 0.0430
Epoch 7/100
75/75 [==============================] - 27s 363ms/step - loss: 3.9256 - accuracy: 0.1747 - val_loss: 4.2003 - val_accur

In [133]:
def clean_up_sentence(sentence):
    # tokenize the pattern - split words into array
    sentence_words = nltk.word_tokenize(sentence)
    # stem each word - create short form for word
    sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]
    return sentence_words
# return bag of words array: 0 or 1 for each word in the bag that exists in the sentence
def bow(sentence, words, show_details=True):
    # tokenize the pattern
    sentence_words = clean_up_sentence(sentence)
    # bag of words - matrix of N words, vocabulary matrix
    bag = [0]*len(words)
    for s in sentence_words:
        for i,w in enumerate(words):
            if w == s: 
                # assign 1 if current word is in the vocabulary position
                bag[i] = 1
                if show_details:
                    print ("found in bag: %s" % w)
    return(np.array(bag))
def predict_class(sentence, model):
    # filter out predictions below a threshold
    p = bow(sentence, words,show_details=False)
    res = model_lstm.predict(np.array([p]))[0]
    ERROR_THRESHOLD = 0.25
    results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]
    # sort by strength of probability
    results.sort(key=lambda x: x[1], reverse=True)
    return_list = []
    #Response change
    for r in results:
        return_list.append({"intent": classes[r[0]], "probability": str(r[1])})
    return return_list

In [134]:
qn = 'is it fine to exercise with knee pain?'
chatbot_response(qn)

1/1 [==============================] - 0s 405ms/step


IndexError: list index out of range

# # Bidirectional 

In [136]:
from tensorflow.keras.layers import Bidirectional

In [137]:
## Creating model
embedding_vector_features=40
model_bilstm=Sequential()
model_bilstm.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model_bilstm.add(Bidirectional(LSTM(100)))
model_bilstm.add(Dense(len(y_train1[0]),activation='softmax'))
model_bilstm.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model_bilstm.summary())

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_9 (Embedding)     (None, 1064, 40)          200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dense_14 (Dense)            (None, 79)                15879     
                                                                 
Total params: 328,679
Trainable params: 328,679
Non-trainable params: 0
_________________________________________________________________
None


In [138]:
### Finally Training
model_bilstm.fit(X_train1,y_train1,validation_data=(X_test1,y_test1),epochs=50,batch_size=5)

Epoch 1/50
75/75 [==============================] - 32s 399ms/step - loss: 4.3735 - accuracy: 0.0081 - val_loss: 4.3754 - val_accuracy: 0.0000e+00
Epoch 2/50
75/75 [==============================] - 29s 386ms/step - loss: 4.3404 - accuracy: 0.0269 - val_loss: 4.4013 - val_accuracy: 0.0000e+00
Epoch 3/50
75/75 [==============================] - 32s 425ms/step - loss: 4.2752 - accuracy: 0.0323 - val_loss: 4.4844 - val_accuracy: 0.0000e+00
Epoch 4/50
75/75 [==============================] - 33s 436ms/step - loss: 4.0824 - accuracy: 0.0538 - val_loss: 4.3413 - val_accuracy: 0.0215
Epoch 5/50
75/75 [==============================] - 35s 469ms/step - loss: 3.6141 - accuracy: 0.1640 - val_loss: 4.2173 - val_accuracy: 0.0430
Epoch 6/50
75/75 [==============================] - 36s 478ms/step - loss: 2.9825 - accuracy: 0.2634 - val_loss: 4.2428 - val_accuracy: 0.0860
Epoch 7/50
75/75 [==============================] - 37s 488ms/step - loss: 2.5028 - accuracy: 0.3978 - val_loss: 4.2067 - val_accu

In [139]:
def clean_up_sentence(sentence):
    # tokenize the pattern - split words into array
    sentence_words = nltk.word_tokenize(sentence)
    # stem each word - create short form for word
    sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]
    return sentence_words
# return bag of words array: 0 or 1 for each word in the bag that exists in the sentence
def bow(sentence, words, show_details=True):
    # tokenize the pattern
    sentence_words = clean_up_sentence(sentence)
    # bag of words - matrix of N words, vocabulary matrix
    bag = [0]*len(words)
    for s in sentence_words:
        for i,w in enumerate(words):
            if w == s: 
                # assign 1 if current word is in the vocabulary position
                bag[i] = 1
                if show_details:
                    print ("found in bag: %s" % w)
    return(np.array(bag))
def predict_class(sentence, model):
    # filter out predictions below a threshold
    p = bow(sentence, words,show_details=False)
    res = model_bilstm.predict(np.array([p]))[0]
    ERROR_THRESHOLD = 0.25
    results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]
    # sort by strength of probability
    results.sort(key=lambda x: x[1], reverse=True)
    return_list = []
    
    for r in results:
        return_list.append({"intent": classes[r[0]], "probability": str(r[1])})
    return return_list

# # GRU Model

In [140]:
from tensorflow.keras.layers import GRU

In [142]:
## Creating model
embedding_vector_features=40
model_gru=Sequential()
model_gru.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model_gru.add(GRU(100))
model_gru.add(Dense(len(y_train1[0]),activation='softmax'))
model_gru.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model_gru.summary())

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_11 (Embedding)    (None, 1064, 40)          200000    
                                                                 
 gru_1 (GRU)                 (None, 100)               42600     
                                                                 
 dense_16 (Dense)            (None, 79)                7979      
                                                                 
Total params: 250,579
Trainable params: 250,579
Non-trainable params: 0
_________________________________________________________________
None


In [143]:
### Finally Training
model_gru.fit(X_train1,y_train1,validation_data=(X_test1,y_test1),epochs=50,batch_size=5)

Epoch 1/50
75/75 [==============================] - 32s 394ms/step - loss: 4.3694 - accuracy: 0.0134 - val_loss: 4.3696 - val_accuracy: 0.0323
Epoch 2/50
75/75 [==============================] - 31s 408ms/step - loss: 4.3194 - accuracy: 0.0699 - val_loss: 4.3797 - val_accuracy: 0.0430
Epoch 3/50
75/75 [==============================] - 31s 413ms/step - loss: 4.1789 - accuracy: 0.0618 - val_loss: 4.4035 - val_accuracy: 0.0000e+00
Epoch 4/50
75/75 [==============================] - 31s 417ms/step - loss: 3.9114 - accuracy: 0.0833 - val_loss: 4.3942 - val_accuracy: 0.0323
Epoch 5/50
75/75 [==============================] - 32s 432ms/step - loss: 3.6888 - accuracy: 0.1694 - val_loss: 4.2985 - val_accuracy: 0.0323
Epoch 6/50
75/75 [==============================] - 32s 427ms/step - loss: 3.2868 - accuracy: 0.2957 - val_loss: 4.3116 - val_accuracy: 0.0430
Epoch 7/50
75/75 [==============================] - 31s 412ms/step - loss: 2.9063 - accuracy: 0.3468 - val_loss: 4.3268 - val_accuracy: 0.